services:
  db:
    image: postgres:16.3-alpine
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=broccoli
    networks:
      - broccoli_net
  migrator:
    image: migrate/migrate
    environment:
      - DB_DRIVER=postgres
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    networks:
      - broccoli_net
    command: ["--path", "/migrations", "--database", "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/broccoli?sslmode=disable", "up"]
  backend:
    build:
      dockerfile: ./dockerfile
    ports:
      - "5050:5050"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY}
    depends_on:
      - migrator
    networks:
      - broccoli_net
networks:
  broccoli_net: {}
